type SettlementPdfInput = {
  companyName: string;
  settlementNumber: string;
  bookingId: string;
  customerName: string;
  carName: string;
  pickup: string;
  returnInfo: string;
  rentalPrice: number;
  insurancePlanName?: string | null;
  insuranceTotal?: number | null;
  depositAmount: number;
  deductionAmount: number;
  returnedDepositAmount: number;
  reasons: string[];
  notes?: string | null;
};

function cleanText(value: string) {
  return value
    .replace(/[^\x20-\x7E]/g, "")
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)");
}

function line(text: string, x: number, y: number, size = 11) {
  return `BT /F1 ${size} Tf ${x} ${y} Td (${cleanText(text)}) Tj ET`;
}

export function createSettlementPdf(input: SettlementPdfInput) {
  const lines = [
    line(input.companyName, 50, 790, 18),
    line("Final rental settlement", 50, 765, 16),
    line(`Settlement No: ${input.settlementNumber}`, 50, 735),
    line(`Booking ID: ${input.bookingId}`, 50, 718),
    line(`Issue date: ${new Date().toLocaleDateString("en-GB")}`, 50, 701),
    line(`Customer: ${input.customerName}`, 50, 690),
    line(`Vehicle: ${input.carName}`, 50, 673),
    line(`Pickup: ${input.pickup}`, 50, 656),
    line(`Return: ${input.returnInfo}`, 50, 639),
    line("Financial summary", 50, 605, 14),
    line(`Rental price: EUR ${input.rentalPrice}`, 70, 580),
    ...(input.insurancePlanName
      ? [
          line(
            `Insurance: ${input.insurancePlanName} - EUR ${input.insuranceTotal || 0}`,
            70,
            563
          ),
        ]
      : []),
    line(`Initial deposit: EUR ${input.depositAmount}`, 70, 546),
    line(`Deposit deduction: EUR ${input.deductionAmount}`, 70, 529),
    line(`Deposit returned: EUR ${input.returnedDepositAmount}`, 70, 512),
    line("Return inspection reasons", 50, 495, 14),
    ...(input.reasons.length > 0
      ? input.reasons.map((reason, index) => line(`- ${reason}`, 70, 470 - index * 17))
      : [line("- No return issues selected", 70, 470)]),
  ];

  if (input.notes) {
    const noteLines = input.notes.split("\n").slice(0, 8);
    lines.push(line("Inspection notes", 50, 345, 14));
    noteLines.forEach((note, index) => {
      lines.push(line(note.slice(0, 90), 70, 320 - index * 17));
    });
  }

  lines.push(
    line(
      "This document is a rental settlement summary generated by the booking system.",
      50,
      80,
      9
    )
  );

  const content = lines.join("\n");
  const objects = [
    "1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj",
    "2 0 obj << /Type /Pages /Kids [3 0 R] /Count 1 >> endobj",
    "3 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >> endobj",
    "4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj",
    `5 0 obj << /Length ${Buffer.byteLength(content)} >> stream\n${content}\nendstream endobj`,
  ];

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  objects.forEach((object) => {
    offsets.push(Buffer.byteLength(pdf));
    pdf += `${object}\n`;
  });

  const xrefStart = Buffer.byteLength(pdf);
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += "0000000000 65535 f \n";
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, "0")} 00000 n \n`;
  });
  pdf += `trailer << /Size ${objects.length + 1} /Root 1 0 R >>\n`;
  pdf += `startxref\n${xrefStart}\n%%EOF`;

  return Buffer.from(pdf);
}
